'use strict';
(()=>{
  document.body.classList.add('fair-banter-v4');
  const style=document.createElement('style');
  style.textContent='.fair-banter-v4 .actor-bubble:not(.fair-bubble){display:none!important}.main-banter{z-index:30!important;max-width:min(300px,58vw)!important}.main-banter::before{content:attr(data-speaker);display:block;font-size:10px;font-weight:900;letter-spacing:.12em;margin-bottom:4px;opacity:.72}.fair-bubble::after{left:var(--tail-x,50%)!important}.fair-bubble.consultant{box-shadow:inset 0 0 0 1px #8bb0c788}.fair-bubble.internal{box-shadow:inset 0 0 0 1px #c59b7288}';document.head.append(style);
  const pools={
    techServicesDirector:["L’intercontrat est à 0 dans le PowerPoint. Dans l’open space, il a encore une chaise.","J’ai demandé de réduire le bench. On a renommé le fichier « capacité disponible ».","La marge progresse. Les salaires ont été priés de ne pas perturber la tendance.","On vise 0 % d’intercontrat. J’ai commencé par supprimer la décimale.","Le taux d’activité remonte. Les consultants aussi, dès qu’un client appelle.","J’ai un plan de staffing très solide. Il ne lui manque que des missions.","Salaire versus marge : enfin un graphique où une barre a le droit de monter.","On industrialise le staffing. Pour l’instant, chaque urgence est industrialisée.","Les compétences sont là. Les budgets clients ont activé le télétravail.","J’ai demandé un plan d’action. J’ai reçu un tableau qui suit le plan d’action.","Le service est critique. Le budget, lui, est facultatif.","Le plan de charge est plein. Principalement de plans de charge."],
    hugo:["Le client voulait un senior. Le commercial a dit oui, puis il m’a appelé.","Mon TJM a pris 12 %. Mon salaire a reçu le compte rendu.","Je suis devenu expert le jour où le commercial a ouvert mon CV.","J’ai trois managers. Aucun ne sait chez quel client je suis."],
    nora:["Le client m’appelle référente. Ma fiche de paie préfère rester discrète.","J’ai changé de mission. Mon salaire, lui, est très fidèle.","Ma revalorisation passe au prochain comité. Le comité aussi, apparemment.","Le client me facture senior. Ma fiche de paie n’a pas reçu le mémo."],
    hugo2:["Le client demandait cinq ans d’expérience. J’en ai trois et un CV très motivé.","Mon onboarding dure plus longtemps que ma première mission.","J’ai enfin les accès. Le projet migre demain.","Le CRA sait exactement où je travaille. C’est déjà quelqu’un."],
    nora2:["Je suis arrivée pour renforcer l’équipe. L’équipe est partie entre-temps.","Le client dit que je suis indispensable. Mon ordre de mission dit vendredi.","J’ai deux certifications et toujours pas le bon VPN.","La mission est stratégique. Le budget de formation est plus opérationnel."],
    basile:["Le client veut baisser le TJM. J’ai proposé d’augmenter la valeur sur la slide.","J’ai trois CV à envoyer avant midi. Aucun n’est disponible avant septembre.","Le pipeline est vert. Les signatures utilisent une palette plus prudente.","J’ai trouvé le profil parfait. Il est donc déjà en mission."],
    basile2:["Le forecast est précis, tant qu’on ne regarde ni les dates ni les montants.","J’ai une ressource disponible. Le besoin vient de passer en pause stratégique.","Le client veut un expert rare au prix d’un junior courant. Classique premium.","J’ai mis « forte probabilité ». « On verra » faisait moins CRM."],
    lea:["Le client veut quelqu’un demain. J’ai demandé si lundi était encore demain.","J’ai vendu une régie. DIRECTEUR DE PROJETS a découvert un forfait.","Le TJM est négociable. Curieusement, jamais vers le haut chez le client.","Le pipeline est « très chaud » depuis assez longtemps pour payer un loyer."],
    lea2:["Le besoin est prioritaire depuis assez longtemps pour devenir patrimonial.","Le CV est validé. Il reste à trouver la personne qui correspond au CV.","Le client veut démarrer lundi. On négocie encore l’année.","Le staffing est aligné : chacun attend la validation de quelqu’un d’autre."],
    sarah:["Le séminaire promet de libérer notre potentiel. Mon agenda reste sous contrôle judiciaire.","J’ai voté pour l’atelier le plus court. Il dure deux heures et un icebreaker.","Le networking commence exactement quand les petits fours arrivent.","J’ai un badge VIP. Toujours pas l’enveloppe qui va avec."],
    mehdi:["On vient de faire un atelier sur les ateliers. Le prochain décidera des suites.","Le Power UP est collectif. Le réveil à 7 h aussi.","J’ai trois photos du séminaire, deux tote bags et zéro décision.","Le plan d’action tient sur une slide. Les actions tiennent jusqu’à lundi."],
    elodie:["Le keynote dit « accélérer ». Le programme finit à 22 h 30.","J’ai gagné un tote bag. La marge peut dormir tranquille.","On nous demande de penser autrement, mais uniquement dans le template officiel.","Le buffet est en libre-service. Enfin une délégation budgétaire."],
    antoine:["Le rooftop est inspirant. Surtout pour vérifier combien il reste d’étages avant la sortie.","J’ai réseauté avec mon équipe. On se revoit demain au bureau.","La plénière se termine par des questions. Personne n’a voulu compromettre sa carrière.","Le séminaire est une réussite : le PowerPoint a démarré du premier coup."],
    projectDirector:["Le planning est au vert. J’ai retiré la colonne « date réelle ».","Le client veut un chiffrage ferme sur un besoin flou. J’ai mis deux décimales, ça rassure.","J’ai passé le risque rouge en orange. La gouvernance vient de gagner un sprint.","Le commerce a vendu vendredi. J’ai découvert lundi que j’étais directeur du projet.","J’ai ajouté un COPIL pour décider comment réduire le nombre de COPIL.","Le projet a trois semaines de retard. Le reporting, lui, est parfaitement à l’heure.","Le client demande une date. J’ai répondu « trajectoire ».","Le staffing est validé. Il manque seulement les gens, les dates et le budget."],
    businessManager:["J’ai vendu un junior en senior. Chez le client, l’expérience passe plus vite.","Le client voulait un expert. J’ai trouvé quelqu’un de disponible : presque pareil dans le CRM.","J’ai augmenté le TJM. Pour le salaire, mon rôle est soudain devenu très technique.","Il est en intercontrat depuis lundi. Depuis mardi, c’est un expert IA.","J’ai promis un profil rare. DIRECTEUR DE PROJETS cherche encore dans quel référentiel.","Le client veut trois personnes lundi. J’ai déjà trouvé le lundi.","Le besoin n’est pas flou : il est agile commercialement.","J’ai sécurisé l’opportunité. Maintenant il faut sécuriser quelqu’un pour la faire."],
    regionalDirector:["Une augmentation ? J’ai justement un budget pour un séminaire sur l’engagement.","Les caisses sont vides. Le budget mobilier, lui, est en pleine transformation.","On ne dit pas non. On dit « à rechallenger au prochain exercice ».","Votre engagement reste notre variable la mieux financée.","J’ai demandé un effort collectif. Le collectif a bien reçu la demande.","Le budget est gelé. Sauf pour les priorités stratégiques que je viens d’ajouter.","La NAO est ouverte. La marge de manœuvre, beaucoup moins.","On va faire plus avec moins. Pour le « plus », je reviens vers vous." ]
  };
  const labels={techServicesDirector:'DIRECTEUR TECHNOLOGIES SERVICES',projectDirector:'DIRECTEUR DE PROJETS',businessManager:'BUSINESS MANAGER',regionalDirector:'DIRECTEUR RÉGION GRAND OUEST'},main={};
  for(const [i,speaker] of ['techServicesDirector','projectDirector','businessManager','regionalDirector'].entries()){const el=document.createElement('div');el.className='actor-bubble fair-bubble main-banter '+speaker;el.dataset.speaker=labels[speaker];el.hidden=true;document.body.append(el);main[speaker]={el,last:-1,until:0,next:performance.now()+1400+i*2200,shownAt:0,dx:0,dy:0};}
  const bubbles=new Map(),make=(id,cls)=>{if(bubbles.has(id)){const b=bubbles.get(id);b.el.className='actor-bubble fair-bubble '+cls;return b;}const el=document.createElement('div');el.className='actor-bubble fair-bubble '+cls;el.hidden=true;document.body.append(el);const b={el,until:0,next:performance.now()+1800+Math.random()*3500,last:-1,lastShown:-Math.random()*5000,shownAt:0,dx:0,dy:0};bubbles.set(id,b);return b;};
  const pick=(pool,last)=>{let i=Math.floor(Math.random()*pool.length);if(pool.length>1&&i===last)i=(i+1+Math.floor(Math.random()*(pool.length-1)))%pool.length;return i;},clamp=(v,lo,hi)=>Math.max(lo,Math.min(hi,v)),onscreen=pos=>pos&&Number.isFinite(pos.x)&&Number.isFinite(pos.y)&&pos.x>=0&&pos.x<=innerWidth&&pos.y>=0&&pos.y<=innerHeight,overlaps=(a,b,pad=8)=>a.left<b.right+pad&&a.right>b.left-pad&&a.top<b.bottom+pad&&a.bottom>b.top-pad,hideAll=()=>{for(const b of bubbles.values())b.el.hidden=true;};let lastState=null;
  function resetLayout(b){b.dx=0;b.dy=0;b.el.style.removeProperty('--tail-x');}
  function placeNearCharacter(b,pos,occupied){if(!onscreen(pos)){b.el.hidden=true;return false;}const el=b.el,mainBubble=el.classList.contains('main-banter'),margin=8;el.hidden=false;el.style.transform='translate(-50%,-115%)';el.style.width=mainBubble?Math.min(300,innerWidth*.58,innerWidth-16)+'px':'';el.style.left=pos.x+'px';el.style.top=pos.y+'px';let initial=el.getBoundingClientRect(),w=initial.width,h=initial.height;if(!w||!h){el.hidden=true;return false;}const reserved=Array.from(document.querySelectorAll?.('.hud,.boss-hud')||[]).filter(e=>!e.hidden).map(e=>e.getBoundingClientRect());const side=Math.min(112,Math.max(54,w*.36)),lift=Math.min(92,Math.max(44,h+12)),below=Math.max(lift*2,...reserved.map(r=>r.bottom-pos.y+h*1.15+12)),raw=[[b.dx||0,b.dy||0],[0,0],[-side,0],[side,0],[0,-lift],[-side*.62,-lift*.52],[side*.62,-lift*.52],[0,below],[-side,below],[side,below]],candidates=[];for(const c of raw)if(!candidates.some(v=>Math.abs(v[0]-c[0])<1&&Math.abs(v[1]-c[1])<1))candidates.push(c);let best=null;for(const [dx,dy] of candidates){let x=clamp(pos.x+dx,margin+w/2,innerWidth-margin-w/2),y=pos.y+dy;el.style.left=x+'px';el.style.top=y+'px';let r=el.getBoundingClientRect();if(r.top<margin){y+=margin-r.top;el.style.top=y+'px';r=el.getBoundingClientRect();}if(r.bottom>innerHeight-16){y-=r.bottom-(innerHeight-16);el.style.top=y+'px';r=el.getBoundingClientRect();}const hits=[...occupied,...reserved].filter(o=>overlaps(r,o)),score=hits.length*10000+Math.abs(x-pos.x)+Math.abs(y-pos.y)*1.15;if(!best||score<best.score)best={x,y,r,score};if(!hits.length)break;}if(best.score>=10000){el.hidden=true;return false;}el.style.left=best.x+'px';el.style.top=best.y+'px';b.dx=best.x-pos.x;b.dy=best.y-pos.y;el.style.setProperty('--tail-x',clamp(pos.x-best.r.left,18,best.r.width-18)+'px');occupied.push(best.r);return true;}
  function reset(now){for(const b of bubbles.values()){b.el.hidden=true;b.until=0;b.next=now+1800+Math.random()*3500;b.lastShown=-Math.random()*5000;b.shownAt=0;resetLayout(b);}['techServicesDirector','projectDirector','businessManager','regionalDirector'].forEach((speaker,i)=>{const b=main[speaker];b.el.hidden=true;b.until=0;b.next=now+1200+i*2200;b.last=-1;b.shownAt=0;resetLayout(b);});}
  function showForced(id,cls,text,pos,now,visible){const b=make(id,cls);if(b.el.textContent!==text){b.el.textContent=text;b.shownAt=now;resetLayout(b);}b.until=now+250;b.next=now+12000;b.lastShown=now;return placeNearCharacter(b,pos,visible);}
  function mainPos(s,speaker){if(speaker==='techServicesDirector'){const boss=globalThis.TechServicesBoss;return s.level===1&&boss&&!boss.defeated(s)?renderer.project(boss.x,surface(4,boss.x)+2,.35):null;}if(speaker==='projectDirector')return renderer.project(s.player.x,s.player.y+2.25,.9);if(speaker==='businessManager')return s.level===2&&s.businessManager?renderer.project(s.businessManager.x,s.businessManager.y+2.35,.4):null;if(speaker==='regionalDirector')return s.level===2&&s.boss&&s.boss.hp>0?renderer.project(s.boss.x,s.boss.y+2.75,.55):null;return null;}
  function updateMain(now,s,occupied,reacting){const active=[];for(const speaker of ['techServicesDirector','projectDirector','businessManager','regionalDirector']){const b=main[speaker],pos=mainPos(s,speaker);if(!s||s.phase!=='playing'||!onscreen(pos)||(reacting&&speaker==='projectDirector')){b.el.hidden=true;continue;}if(now>=b.next){const pool=pools[speaker];b.last=pick(pool,b.last);b.el.textContent=pool[b.last];b.shownAt=now;b.until=now+10000;b.next=b.until+4500+Math.random()*3500;resetLayout(b);}b.el.hidden=now>=b.until;if(!b.el.hidden)active.push({b,pos});}active.sort((a,b)=>a.b.shownAt-b.b.shownAt);for(const item of active){item.b.el.hidden=true;if(occupied.length<2)placeNearCharacter(item.b,item.pos,occupied);}return occupied;}
  function loop(now){const s=typeof Arcade!=='undefined'?Arcade.state:null;if(!s||typeof renderer==='undefined'){requestAnimationFrame(loop);return;}if(s!==lastState){lastState=s;reset(now);}hideAll();if(s.phase!=='playing'){for(const speaker of ['techServicesDirector','projectDirector','businessManager','regionalDirector'])main[speaker].el.hidden=true;requestAnimationFrame(loop);return;}const visible=[],p=s.player,limit=2,reacting=s.comedy?.lineTime>0&&!!s.comedy.line;if(reacting)showForced('projectDirector-script','projectDirector',s.comedy.line,renderer.project(p.x,p.y+2.25,.9),now,visible);updateMain(now,s,visible,reacting);const candidates=[];for(let i=0;i<s.enemies.length;i++){const e=s.enemies[i];if(e.stun>0||Math.abs(e.floor-p.floor)>1)continue;const pos=renderer.project(e.x,e.y+2.05,.45);if(!onscreen(pos))continue;const category=/^(hugo|nora)/.test(e.kind)?'consultant':'internal';candidates.push({id:'emp-'+i,cls:'employee '+category,pool:pools[e.kind]||pools.lea,pos});}candidates.sort((a,b)=>{const ba=make(a.id,a.cls),bb=make(b.id,b.cls),aa=now<ba.until,ab=now<bb.until;if(aa!==ab)return aa?-1:1;return ba.lastShown-bb.lastShown;});for(const c of candidates){if(visible.length>=limit)break;const b=make(c.id,c.cls);if(now>=b.until&&now<b.next)continue;if(now>=b.next){b.last=pick(c.pool,b.last);b.el.textContent=c.pool[b.last];b.shownAt=now;b.until=now+10000+Math.random()*2000;b.next=b.until+8500+Math.random()*4500;b.lastShown=now;resetLayout(b);}if(now>=b.until)continue;placeNearCharacter(b,c.pos,visible);}requestAnimationFrame(loop);}requestAnimationFrame(loop);
})();