'use strict';
(()=>{
  if(!renderer?.gl||typeof renderer.draw!=='function')return;
  const gl=renderer.gl;
  const rawDrawArrays=gl.drawArrays.bind(gl),rawBindTexture=gl.bindTexture.bind(gl);
  let textureBindIndex=0,inRendererDraw=false;

  gl.bindTexture=function(target,texture){
    if(inRendererDraw&&target===gl.TEXTURE_2D&&texture)textureBindIndex++;
    return rawBindTexture(target,texture);
  };
  gl.drawArrays=function(mode,first,count){
    // The fourth textured sign is the legacy +3 % face attached to Basile.
    if(inRendererDraw&&textureBindIndex===4&&mode===gl.TRIANGLES&&count===6)return;
    return rawDrawArrays(mode,first,count);
  };

  const originalDraw=renderer.draw.bind(renderer);
  renderer.draw=function(dt){
    textureBindIndex=0;
    inRendererDraw=true;

    // Basile's old placard is made of two separate things: a textured face and
    // a brown board/pole generated by the `union` render branch. Keep his
    // gameplay type untouched, but make that branch invisible for rendering.
    const basile=Arcade?.state?.enemies?.find(e=>e.kind==='basile');
    const basileStun=basile?.stun;
    const hideBoard=!!basile&&basileStun<=0;
    if(hideBoard)basile.stun=Number.NaN;

    try{return originalDraw(dt);}finally{
      if(hideBoard)basile.stun=basileStun;
      inRendererDraw=false;
    }
  };

  // Position and size the DOM glasses from Rodolphe's actual projected eyes.
  // There is no title/game size preset: resizing the browser automatically
  // rescales the glasses in exactly the same proportion as the 3D character.
  const reduced=matchMedia('(prefers-reduced-motion: reduce)');
  function syncRodolphe(){
    const s=Arcade?.state,glasses=document.querySelector('.rodolphe-glasses'),name=document.querySelector('.rodolphe-name-fix');
    if(s&&glasses&&renderer){
      const visible=s.boss.hp>0&&!['help','records','paused','won','lost'].includes(s.phase);
      glasses.hidden=!visible;
      if(name)name.hidden=!visible||s.phase==='title';
      if(visible){
        const rowing=!s.boss.active&&Math.floor(s.visual/6)%2===1;
        const bossX=s.boss.x-(s.boss.recoil>0?.24*(s.boss.recoil/.28):0);
        const drawX=bossX+(rowing?Math.sin(s.visual*6)*.18:0);
        const bounce=rowing&&!reduced.matches?Math.abs(Math.sin(s.visual*7))*.48:0;
        const scale=1.27;
        const eyeY=s.boss.y+.32+bounce+1.16*scale;
        const eyeZ=.15+.19*scale;
        const eyeHalf=.105*scale;
        const face=renderer.project(drawX,eyeY,eyeZ);
        const leftEye=renderer.project(drawX-eyeHalf,eyeY,eyeZ);
        const rightEye=renderer.project(drawX+eyeHalf,eyeY,eyeZ);
        const projectedEyeGap=Math.hypot(rightEye.x-leftEye.x,rightEye.y-leftEye.y);

        // With border-box sizing the DOM lens centres are 19 px apart at scale 1.
        // Match that separation to the projected 3D eye separation.
        const glassesScale=Math.max(.28,Math.min(2.4,projectedEyeGap/19));
        glasses.style.left=face.x+'px';
        glasses.style.top=face.y+'px';
        glasses.style.setProperty('transform','translate(-50%,-50%) scale('+glassesScale+')','important');

        if(name&&!name.hidden){
          const np=renderer.project(drawX,s.boss.y+.32+bounce+2.12,.45);
          name.style.left=np.x+'px';
          name.style.top=np.y+'px';
        }

        // game.js still paints its original RODOLPHE label on the overlay canvas.
        // Erase that exact static label after each frame; the raised DOM label above
        // remains the single visible name. Do not add the character bounce here:
        // the legacy canvas label itself does not bounce with Rodolphe.
        const overlay=document.getElementById('overlay');
        if(overlay){
          const ctx=overlay.getContext('2d');
          const ratio=Math.min(devicePixelRatio||1,1.5);
          const legacy=renderer.project(s.boss.x,s.boss.y+2.05,.65);
          ctx.save();
          ctx.setTransform(ratio,0,0,ratio,0,0);
          ctx.clearRect(legacy.x-64,legacy.y-16,128,32);
          ctx.restore();
        }
      }
    }
    requestAnimationFrame(syncRodolphe);
  }
  requestAnimationFrame(syncRodolphe);
})();
