'use strict';
(()=>{
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const lowPerf=(navigator.hardwareConcurrency&&navigator.hardwareConcurrency<=4)||(navigator.deviceMemory&&navigator.deviceMemory<=4)||innerWidth<700;
  if(lowPerf)document.body.classList.add('perf-low');
  const contrastButton=document.getElementById('contrastButton');
  contrastButton?.addEventListener('click',()=>{const on=document.body.classList.toggle('high-contrast');contrastButton.setAttribute('aria-pressed',String(on));contrastButton.textContent=on?'◐ Contraste +':'◐ Contraste';});

  const bossHud=document.createElement('div');bossHud.className='boss-hud';bossHud.hidden=true;bossHud.innerHTML='<div class="boss-hud-title"><span>RODOLPHE · DIRECTEUR</span><span id="bossHpText">3 / 3</span></div><div class="boss-track"><div class="boss-fill" id="bossFill"></div></div>';document.body.append(bossHud);
  const bossFill=bossHud.querySelector('#bossFill'),bossHpText=bossHud.querySelector('#bossHpText');
  const cinema=document.createElement('div');cinema.className='cinematic-card';cinema.hidden=true;cinema.innerHTML='<div class="cinematic-copy"><small></small><strong></strong><em></em><span class="cinematic-hint"></span></div>';document.body.append(cinema);
  const cinemaSmall=cinema.querySelector('small'),cinemaStrong=cinema.querySelector('strong'),cinemaEm=cinema.querySelector('em'),cinemaHint=cinema.querySelector('.cinematic-hint');
  const worldmark=document.createElement('div');worldmark.className='inetum-worldmark';worldmark.textContent='INETUM';document.body.append(worldmark);
  const decor=[0,1,2].map(()=>{const el=document.createElement('div');el.className='level-decor';document.body.append(el);return el;});
  const rodolpheGlasses=document.createElement('div');rodolpheGlasses.className='rodolphe-glasses';rodolpheGlasses.innerHTML='<i></i><b></b><i></i>';document.body.append(rodolpheGlasses);
  const rodolpheName=document.createElement('div');rodolpheName.className='rodolphe-name-fix';rodolpheName.textContent='RODOLPHE';document.body.append(rodolpheName);
  const titleRodolphe=document.querySelector('.title-person.rodolphe');if(titleRodolphe){const g=document.createElement('span');g.className='title-glasses';g.innerHTML='<i></i><b></b><i></i>';titleRodolphe.append(g);}
  const tags=[];const ensureTag=(i,type)=>{if(!tags[i]){const el=document.createElement('div');el.className='projectile-tag';document.body.append(el);tags[i]=el;}const el=tags[i];el.className='projectile-tag '+type;el.textContent=type==='cr'?'CR':'DOSSIER';el.hidden=false;el.style.transform=type==='cr'?'translate(-50%,-50%) rotate(-4deg)':'translate(-50%,-50%) rotate(8deg)';return el;};const hideTagsFrom=i=>{for(let n=i;n<tags.length;n++)tags[n].hidden=true;};
  const levelCopy=[['NIVEAU 1','OPEN SPACE','Le salaire émotionnel ne paie pas le loyer.'],['NIVEAU 2','LA DIRECTION','Ici, même les décisions ont besoin d’une réunion.'],['NIVEAU 3','ROOFTOP DU SÉMINAIRE','Dernier atelier : reprendre le budget.']];
  const decorCopy=[['CRA À VALIDER','OPEN SPACE'],['KPI · COMEX','OBJECTIF 140 %'],['SÉMINAIRE','BUDGET 2027']];
  const banter={hugo:['Le client voulait un senior. Le commercial a dit oui, puis il m’a appelé.','Mon TJM a pris 12 %. Mon salaire a pris connaissance de l’information.','Je suis “expert” depuis que le commercial a modifié mon CV.','J’ai trois managers. Aucun ne sait sur quel projet je suis.','On m’a vendu autonome. Je cherche encore les accès.','La mission est “longue durée”. Mon badge expire vendredi.'],nora:['Le client m’appelle référente. Ma fiche de paie reste plus modeste.','J’ai changé de mission. Mon salaire, lui, est très fidèle.','La revalorisation arrive après le prochain comité. Le comité aussi, apparemment.','Je facture assez pour éviter de faire le calcul.','On m’a proposé de devenir manager. J’ai demandé combien. Fin de la discussion.','Mon objectif annuel : comprendre mon variable avant décembre.'],basile:['Le variable est surtout variable au moment de le verser.','On est une grande famille. Une famille qui facture mes heures au client.','La NAO commence dès qu’on retrouve le budget. Le budget est porté disparu.','Ils ont remplacé l’augmentation par un webinar bien-être.','Bonne nouvelle : le panier repas a gagné 14 centimes.','J’ai demandé l’inflation. On m’a proposé une formation LinkedIn.'],lea:['Le commerce a vendu deux jours. J’en suis à ma troisième semaine.','J’ai livré vendredi. Ils ont découvert le besoin lundi.','La mission est stratégique. Personne n’a retrouvé le cahier des charges.','On m’a dit “quick win”. J’ai ouvert mon CV.','Le staffing m’a appelée pour une urgence prévue depuis mars.','Le client veut quelqu’un demain. Le commercial demande si je connais Kubernetes.'],kevin:['J’ai mis “urgent” dans l’objet. Ça compte comme pilotage.','Le planning tient parfaitement si personne ne regarde les dates.','J’ai passé le risque rouge en orange. Gouvernance maîtrisée.','Le client veut un chiffrage ferme sur un besoin flou. On est bien.','J’attends le retour du commerce depuis le sprint 4.','J’ai ajouté une réunion pour comprendre pourquoi on a trop de réunions.','Le budget est gelé, mais le reporting est en croissance.','Je vais escalader. Littéralement, cette fois.'],charline:['Ils ont dit “petit atelier”. Il y a 47 slides et un icebreaker.','Le budget est bloqué, mais le séminaire avait des tote bags.','Quelqu’un vient de dire “quick win”. Je commence à avoir peur.','On fait un REX sur le REX du dernier REX.','Ils ont vendu deux jours. Je fête bientôt mon premier mois.','Le directeur a dit “synergie”. Personne n’a osé demander avec quoi.','J’ai demandé une augmentation. On m’a envoyé le catalogue de formations.','Le prochain atelier s’appelle “alignement”. On n’est déjà plus alignés.']};
  const bubbles={};function bubbleFor(id,cls){if(!bubbles[id]){const el=document.createElement('div');el.className='actor-bubble '+cls;el.hidden=true;document.body.append(el);bubbles[id]={el,until:0,next:performance.now()+Math.random()*3500+1800,line:-1};}return bubbles[id];}function pickLine(pool,last){let i=Math.floor(Math.random()*pool.length);if(pool.length>1&&i===last)i=(i+1+Math.floor(Math.random()*(pool.length-1)))%pool.length;return i;}function scheduleBubble(id,cls,pool,pos,now,active=true,min=5200,max=9200){const b=bubbleFor(id,cls);if(!active||!pos){b.el.hidden=true;return;}if(now>=b.next){b.line=pickLine(pool,b.line);b.el.textContent=pool[b.line];b.until=now+2600+Math.random()*1000;b.next=b.until+min+Math.random()*(max-min);}if(now<b.until){b.el.hidden=false;b.el.style.left=Math.max(125,Math.min(innerWidth-125,pos.x))+'px';b.el.style.top=Math.max(120,Math.min(innerHeight-35,pos.y))+'px';}else b.el.hidden=true;}function hideAllBubbles(){Object.values(bubbles).forEach(b=>b.el.hidden=true);}
  let lastLevel=-1,bossIntroSeen=false,cinemaTimer=null,finaleSeen=false,waitingIntro=false,introState=null;
  function closeCinema(){if(cinemaTimer){clearTimeout(cinemaTimer);cinemaTimer=null;}cinema.classList.remove('show');const s=Arcade.state,setPlaying=introState&&s===introState&&['levelIntro','bossIntro'].includes(s.phase);setTimeout(()=>{cinema.hidden=true;},reduced?0:180);if(setPlaying){s.phase='playing';document.body.dataset.phase='playing';}waitingIntro=false;introState=null;}
  function cinematic(kind,small,strong,em,duration=1050,freeze=true,waitForInput=false){if(cinemaTimer)clearTimeout(cinemaTimer);const s=Arcade.state,previous=s.phase;if(freeze&&previous==='playing'){Arcade.keys.clear();s.phase=kind;document.body.dataset.phase=kind;}introState=s;waitingIntro=waitForInput;cinema.className='cinematic-card '+(kind==='bossIntro'?'boss-intro':kind==='finale'?'finale-intro':'level-intro');cinemaSmall.textContent=small;cinemaStrong.textContent=strong;cinemaEm.textContent=em;cinemaHint.textContent=waitForInput?'APPUYEZ SUR UNE TOUCHE OU CLIQUEZ POUR CONTINUER':'';cinema.hidden=false;if(!reduced)requestAnimationFrame(()=>cinema.classList.add('show'));else cinema.classList.add('show');if(!waitForInput)cinemaTimer=setTimeout(closeCinema,reduced?Math.min(duration,650):duration);}
  const dismissIntro=e=>{if(!waitingIntro)return;if(e.type==='keydown'&&['Shift','Control','Alt','Meta'].includes(e.key))return;e.preventDefault();e.stopPropagation();closeCinema();};document.addEventListener('keydown',dismissIntro,true);document.addEventListener('pointerdown',dismissIntro,true);
  function positionDecor(s){const coords=s.level===0?[[-6,3.7],[-1,7],[5,10.1]]:s.level===1?[[-6,4],[0,7.2],[5.5,10.2]]:[[-6,4.1],[0,7.2],[5.5,10.1]];decor.forEach((el,i)=>{const pos=renderer.project(coords[i][0],coords[i][1],-1);el.style.left=pos.x+'px';el.style.top=pos.y+'px';el.className='level-decor '+(s.level===0?'open':s.level===1?'direction':'rooftop');el.textContent=decorCopy[s.level][i%2];el.hidden=s.phase==='title'||pos.x<0||pos.x>innerWidth||pos.y<80||pos.y>innerHeight;});}
  function updateBanter(s,now){for(const e of s.enemies)e.talk=0;s.charlineTalk=0;if(s.phase!=='playing'){hideAllBubbles();return;}const p=s.player,kevin=renderer.project(p.x,p.y+2.25,.9),charline=renderer.project(s.princess.x,s.princess.y+2.35,.4);scheduleBubble('kevin','kevin',banter.kevin,kevin,now,true,6500,10500);scheduleBubble('charline','charline',banter.charline,charline,now,true,7200,11500);for(let i=0;i<s.enemies.length;i++){const e=s.enemies[i],pos=renderer.project(e.x,e.y+2.05,.45);scheduleBubble('emp-'+i,'employee',banter[e.kind]||banter.lea,pos,now,e.stun<=0,4800,8800);}}
  function positionRodolphe(s){const visible=s.boss.hp>0&&!['title','help','records'].includes(s.phase);rodolpheGlasses.hidden=rodolpheName.hidden=!visible;if(!visible)return;const face=renderer.project(s.boss.x,s.boss.y+1.78,.8),name=renderer.project(s.boss.x,s.boss.y+2.62,.8);rodolpheGlasses.style.left=face.x+'px';rodolpheGlasses.style.top=face.y+'px';rodolpheName.style.left=name.x+'px';rodolpheName.style.top=name.y+'px';const overlay=document.getElementById('overlay');if(overlay){const ctx=overlay.getContext('2d'),ratio=Math.min(devicePixelRatio||1,1.5),old=renderer.project(s.boss.x,s.boss.y+2.05,.65);ctx.save();ctx.setTransform(ratio,0,0,ratio,0,0);ctx.clearRect(old.x-48,old.y-11,96,22);ctx.restore();}}
  function update(){const s=Arcade.state;if(!s||!renderer){requestAnimationFrame(update);return;}if(s.phase==='playing'&&s.level!==lastLevel){lastLevel=s.level;bossIntroSeen=false;finaleSeen=false;const [a,b,c]=levelCopy[s.level];cinematic('levelIntro',a,b,c,0,true,true);}if(s.boss.active&&s.boss.hp>0){bossHud.hidden=false;bossFill.style.width=(s.boss.hp/3*100)+'%';bossHpText.textContent=s.boss.hp+' / 3';bossHud.classList.toggle('vulnerable',!!s.boss.open);if(!bossIntroSeen&&s.level===2&&s.phase==='playing'){bossIntroSeen=true;cinematic('bossIntro','BOSS FINAL','RODOLPHE','DIRECTEUR · GARDIEN DU BUDGET',1250,true,false);}}else bossHud.hidden=true;if(s.phase==='won'&&!finaleSeen){finaleSeen=true;cinematic('finale','CHARLINE EST LIBÉRÉE','BUDGET DÉBLOQUÉ','POUR TOUS LES EMPLOYÉS',reduced?700:1550,false,false);}let i=0;for(const p of s.papers){const pos=renderer.project(p.x,p.y,.98),el=ensureTag(i++,'cr');el.style.left=pos.x+'px';el.style.top=pos.y+'px';}for(const h of s.hostile){if(h.kind!=='boss')continue;const pos=renderer.project(h.x,h.y,.98),el=ensureTag(i++,'dossier');el.style.left=pos.x+'px';el.style.top=pos.y+'px';el.style.transform='translate(-50%,-50%) rotate('+(h.reflected?'-8deg':'8deg')+')';}hideTagsFrom(i);const mark=renderer.project(-4,13.6,-1.08);worldmark.style.left=mark.x+'px';worldmark.style.top=mark.y+'px';worldmark.hidden=mark.x<0||mark.x>innerWidth||mark.y<0||mark.y>innerHeight;positionDecor(s);updateBanter(s,performance.now());positionRodolphe(s);if(lowPerf&&s.particles&&s.particles.length>90)s.particles.splice(0,s.particles.length-90);if(reduced){s.impact=0;s.hitFlash=Math.min(s.hitFlash||0,.04);}requestAnimationFrame(update);}requestAnimationFrame(update);
})();
