const {test}=require('node:test');
const assert=require('node:assert/strict');
const {readFileSync,existsSync}=require('node:fs');
const {join}=require('node:path');

const root=join(__dirname,'..');
const read=file=>readFileSync(join(root,file),'utf8');
const has=(source,text,message)=>assert.ok(source.includes(text),message||`missing: ${text}`);
const lacks=(source,text,message)=>assert.ok(!source.includes(text),message||`unexpected: ${text}`);

test('canonical roles and story are visible in the entry point',()=>{const html=read('index.html');for(const x of ['Tu incarnes le Directeur de Projets','La Business Manager est coincée au séminaire.','Directeur Technologies Services Pays de la Loire','Directeur Région Grand Ouest','TOUT EST SOUS CONTRÔLE. MÊME LE BUDGET.','Niveau 1 : retrouve la trace de la Business Manager','Niveau 2 : renvoie les KPI','Niveau 3 : affronte le Directeur Région Grand Ouest'])has(html,x);});
test('BUSINESS MANAGER and DIRECTEUR RÉGION GRAND OUEST are reserved for the final level in the native runtime',()=>{const game=read('game.js'),banter=read('banter-fair.js');for(const x of ["if(s.level===2)person(moving,'businessManager'","if(s.level===2){moving.box(s.boss.x","if(s.level===2&&s.businessManagerIn<=0)","if(s.level===2)label('BUSINESS MANAGER'","if(s.level===2)label('DIRECTEUR RÉGION GRAND OUEST'"])has(game,x);has(banter,"s.level===2&&s.businessManager");has(banter,"s.level===2&&s.boss");});
test('legacy DIRECTEUR RÉGION GRAND OUEST massage-chair scene is absent from production runtime',()=>{const game=read('game.js'),banter=read('banter-fair.js');for(const x of ['deliveryScene','comedy.delivery','.delivered','fauteuils massants'])lacks(game,x);for(const x of ['deliveryScene','raise-request','fauteuils'])lacks(banter,x);});
test('DIRECTEUR TECHNOLOGIES SERVICES guards rooftop access rather than BUSINESS MANAGER',()=>{const techServicesDirector=read('tech-services-boss.js');has(techServicesDirector,'DIRECTEUR TECHNOLOGIES SERVICES BLOQUE L’ACCÈS AU ROOFTOP');has(techServicesDirector,'Math.abs(s.player.x-X)<2.2');lacks(techServicesDirector,'DIRECTEUR TECHNOLOGIES SERVICES BLOQUE BUSINESS MANAGER');});
test('all twelve generic NPC slots are native and unique across the three levels',()=>{const game=read('game.js'),html=read('index.html');for(const roster of ["['hugo','nora','hugo2','lea']","['nora2','basile','basile2','lea2']","['sarah','mehdi','elodie','antoine']"])has(game,roster);has(game,'const LEVEL_ROSTERS=');has(game,'const roster=LEVEL_ROSTERS[s.level]');assert.equal(new Set(['hugo','nora','hugo2','lea','nora2','basile','basile2','lea2','sarah','mehdi','elodie','antoine']).size,12);lacks(html,'population-levels.js');assert.equal(existsSync(join(root,'population-levels.js')),false);});
test('all seminar cast lives natively in game.js',()=>{const game=read('game.js'),html=read('index.html');for(const [key,name] of [['sarah','Sarah'],['mehdi','Mehdi'],['elodie','Élodie'],['antoine','Antoine']])has(game,`CAST.${key}={name:'${name}'`);lacks(html,'unique-cast-preload.js');lacks(html,'game-loader.js');assert.equal(existsSync(join(root,'unique-cast-preload.js')),false);assert.equal(existsSync(join(root,'game-loader.js')),false);has(html,'game.js?v=53');});
test('consultants and internal/business NPCs keep distinct visual and dialogue families',()=>{const game=read('game.js'),banter=read('banter-fair.js');has(game,"category:'consultant'");has(game,"category:'business'");for(const x of ["CAST.hugo2={name:'Mathis'","CAST.nora2={name:'Inès'","CAST.basile2={name:'Thomas'","CAST.lea2={name:'Camille'"])has(game,x);for(const key of ['hugo2','nora2','basile2','lea2','sarah','mehdi','elodie','antoine'])has(banter,`${key}:[`);lacks(banter,'pools.hugo2=pools.hugo');has(banter,"/^(hugo|nora)/.test(e.kind)?'consultant':'internal'");has(banter,'Le pipeline est vert. Les signatures utilisent une palette plus prudente.');});
test('game.js is the canonical directly loaded runtime',()=>{const game=read('game.js'),html=read('index.html');for(const x of ['princess','deliveryScene','comedy.delivery','.delivered'])lacks(game,x);has(game,'Object.defineProperties(globalThis,{Arcade:');has(game,'globalThis.OfficeDecor.draw(world,sign,level,surface)');has(html,'<script src="game.js?v=53"></script>');lacks(html,'game-loader.js');});
test('budget language is native and distinguishes project protection from the final budget',()=>{const game=read('game.js'),signage=read('corporate-signage.js'),html=read('index.html'),polish=read('polish.js');for(const x of ['BON DE COMMANDE','ARBITRAGE 1 / 3','ARBITRAGE 2 / 3'])has(game,x);lacks(game,'BUDGET VALIDÉ');has(signage,'signage/bon-commande.png');lacks(html,'budget-semantics.js');assert.equal(existsSync(join(root,'budget-semantics.js')),false);has(polish,'DIRECTEUR RÉGION GRAND OUEST');});
test('polish owns presentation only and has no legacy BUSINESS MANAGER or delivery runtime',()=>{const p=read('polish.js');for(const x of ['DIRECTEUR RÉGION GRAND OUEST',"['NIVEAU 1','OPEN SPACE · LCP7'","['NIVEAU 2','DIRECTION TECHNOLOGIES SERVICES'","['NIVEAU 3','POWER UP TOUR · GRAND OUEST'","s.level===2&&s.boss.active&&s.boss.hp>0",'DÉBLOQUE LE BUDGET POUR TOUS'])has(p,x);for(const x of ['s.princess','deliveryScene','comedy.delivery','updateBanter','const banter='])lacks(p,x);});
test('ambient quips have a safe fallback for every unique NPC kind',()=>{const game=read('game.js');has(game,"QUIPS[e.kind]||(CAST[e.kind]?.category==='consultant'?QUIPS.hugo:QUIPS.lea)");lacks(game,'QUIPS[e.kind][e.line]');});
test('legacy generic signage is absent from the canonical renderer',()=>{const game=read('game.js'),signage=read('corporate-signage.js');for(const x of ['INETUM_DECOR','cardRows=','Inetum decor is actual textured geometry',"title:'SUCCESS FACTORS'","title:'GLOBAL SERVICE CENTER'","title:'SUMMER PARTY'"])lacks(game,x);lacks(signage,'function cooptation');has(read('special-signage.js'),'cooptation.png');});
test('final presentation has a single DIRECTEUR RÉGION GRAND OUEST owner and no per-frame dialogue cleanup layer',()=>{const polish=read('polish.js'),game=read('game.js'),html=read('index.html');has(polish,'projectedEyeGap');has(polish,'glassesScale');lacks(game,'businessManagerTalk');lacks(game,'businessManagerLine');lacks(game,'businessManager_LINES');has(game,'LA MARGE EST AU VERT. C’EST L’ESSENTIEL.');has(game,'REFUSÉ. MAIS MERCI POUR L’ENGAGEMENT.');lacks(html,'cleanup.js');lacks(html,'main-dialogue-cleanup.js');assert.equal(existsSync(join(root,'cleanup.js')),false);assert.equal(existsSync(join(root,'main-dialogue-cleanup.js')),false);assert.equal(existsSync(join(root,'roles-polish.js')),false);});
test('DIRECTEUR RÉGION GRAND OUEST budget safe is owned by polish and dies with the boss',()=>{const polish=read('polish.js'),html=read('index.html');has(polish,"className='regionalDirector-safe'");has(polish,'s.boss.hp>0');has(polish,'regionalDirectorSafe.hidden=!visible');lacks(html,'roles-polish.js');assert.equal(existsSync(join(root,'roles-polish.js')),false);});
