"""Build the file:// PNG bundle for the three special signs (Pillow required)."""
from pathlib import Path
from PIL import Image
import io, base64, json
root=Path(__file__).resolve().parent.parent
assets={}
for name in ['cooptation.png','POWER_UP_TOUR.png','espace_VIP.png']:
    with Image.open(root/'signage'/name) as image:
        output=io.BytesIO()
        image.convert('RGBA').quantize(colors=256,method=Image.Quantize.FASTOCTREE,dither=Image.Dither.NONE).save(output,format='PNG',optimize=True)
    assets[name]='data:image/png;base64,'+base64.b64encode(output.getvalue()).decode('ascii')
(root/'special-signage-offline.js').write_text("'use strict';\n// Generated by scripts/generate-offline-special-signage.py; file:// only.\nglobalThis.OfficeSpecialSignageOffline="+json.dumps(assets,separators=(',',':'))+';\n')
