"""Embed full-resolution whiteboards for file:// reading without tainting WebGL (Pillow required)."""
from pathlib import Path
from PIL import Image
import base64
import io
import json

root = Path(__file__).resolve().parent.parent
assets = {}
for number in range(1, 5):
    path = root / 'signage' / f'Whiteboard{number:02}.png'
    with Image.open(path) as image:
        output = io.BytesIO()
        image.convert('RGBA').quantize(colors=256, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE).save(output, format='PNG', optimize=True)
    assets[path.name] = 'data:image/png;base64,' + base64.b64encode(output.getvalue()).decode('ascii')
text = "'use strict';\n// Generated by scripts/generate-offline-whiteboards.py; file:// only.\nglobalThis.OfficeWhiteboardOffline=" + json.dumps(assets, separators=(',', ':')) + ';\n'
(root / 'whiteboards-offline.js').write_text(text)
print(f'4 full-resolution whiteboards: {len(text):,} bytes')
