"""Build local-file-safe signage textures. Requires Pillow; original online PNGs stay intact."""
from pathlib import Path
from PIL import Image
import base64
import io
import json

root = Path(__file__).resolve().parent.parent
assets = {}
for path in sorted((root / 'signage').glob('*.png')):
    with Image.open(path) as original:
        # Half-size source is still several times larger than the in-game panels.
        image = original.convert('RGB').resize((original.width // 2, original.height // 2), Image.Resampling.LANCZOS)
        output = io.BytesIO()
        image.quantize(colors=256, dither=Image.Dither.NONE).save(output, format='PNG', optimize=True)
    assets['signage/' + path.name] = 'data:image/png;base64,' + base64.b64encode(output.getvalue()).decode('ascii')
text = "'use strict';\n// Generated by scripts/generate-offline-signage.py; loaded only for file:// play.\nglobalThis.OfficeSignageOffline=" + json.dumps(assets, separators=(',', ':')) + ';\n'
(root / 'signage-offline.js').write_text(text)
print(f'{len(assets)} offline textures; {len(text):,} bytes')
