const {readFileSync,writeFileSync}=require('node:fs');
let html=readFileSync('index.html','utf8');
const inline='<style>.rodolphe-glasses{transform:translate(-50%,-50%)!important}.rodolphe-glasses i{border-width:3px!important;background:#8fb0bdcc!important}.rodolphe-glasses b{height:3px!important}.rodolphe-name-fix{margin-top:-18px!important;font-size:11px!important;font-weight:900!important}body:not([data-level="2"]) .rodolphe-glasses,body:not([data-level="2"]) .rodolphe-name-fix,body:not([data-level="2"]) .rodolphe-safe,body:not([data-level="2"]) .main-banter.charline,body:not([data-level="2"]) .main-banter.rodolphe{display:none!important}</style>\n';
html=html.replace(inline,'').replace('polish.css?v=17','polish.css?v=18');
writeFileSync('index.html',html);
let css=readFileSync('polish.css','utf8');
const block='\n/* Final-level RORO presentation ownership */\n.rodolphe-glasses{transform:translate(-50%,-50%)!important}\n.rodolphe-glasses i{border-width:3px!important;background:#8fb0bdcc!important}\n.rodolphe-glasses b{height:3px!important}\n.rodolphe-name-fix{margin-top:-18px!important;font-size:11px!important;font-weight:900!important}\nbody:not([data-level="2"]) .rodolphe-glasses,body:not([data-level="2"]) .rodolphe-name-fix,body:not([data-level="2"]) .rodolphe-safe,body:not([data-level="2"]) .main-banter.charline,body:not([data-level="2"]) .main-banter.rodolphe{display:none!important}\n';
if(!css.includes('Final-level RORO presentation ownership'))css+=block;
writeFileSync('polish.css',css);
let cache=readFileSync('tests/cache-version.test.cjs','utf8');
cache=cache.replace("assert.ok(html.includes('game.js?v=43'));assert.ok(html.includes('polish.js?v=25'));assert.equal(html.includes('roles-polish.js'),false);","assert.ok(html.includes('game.js?v=43'));assert.ok(html.includes('polish.js?v=25'));assert.ok(html.includes('polish.css?v=18'));assert.equal(html.includes('roles-polish.js'),false);assert.equal(html.includes('<style>.rodolphe-glasses'),false);");
writeFileSync('tests/cache-version.test.cjs',cache);
